
export const MAINPAGE_TOGGLE_NAVIPANE = 'MAINPAGE_TOGGLE_NAVIPANE';
export const MAINPAGE_TOGGLE_DETAILSPANE = 'MAINPAGE_TOGGLE_DETAILSPANE';
export const MAINPAGE_TOGGLE_THUMBSPANE = 'MAINPAGE_TOGGLE_THUMBSPANE';

export const MAINPAGE_RESIZE_NAVIPANE = 'MAINPAGE_RESIZE_NAVIPANE';
export const MAINPAGE_RESIZE_DETAILSPANE = 'MAINPAGE_RESIZE_DETAILSPANE';
export const MAINPAGE_RESIZE_THUMBSPANE = 'MAINPAGE_RESIZE_THUMBSPANE';

export const IMAGEPANE_NEXT_OBJECT = 'IMAGEPANE_NEXT_OBJECT';
export const IMAGEPANE_PREV_OBJECT = 'IMAGEPANE_PREV_OBJECT';
